# ===============================
# APPLICATION
# ===============================
spring.application.name=CRMERP
server.port=8080

# ===============================
# POSTGRESQL CONFIGURATION
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/crm_erp_db
spring.datasource.username=postgres
spring.datasource.password=raja2004
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# create, update, validate, none
spring.jpa.hibernate.ddl-auto=update

# Afficher les requêtes SQL
spring.jpa.show-sql=false

# Format SQL
spring.jpa.properties.hibernate.format_sql=false

# ===============================
# LOGGING (OPTIONNEL)
# ===============================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE